[workspace]
members = ["aoc-2025", "aoc-2024"]
default-members = ["aoc-2025"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
grid = "1.0.0"
itertools = "0.14.0"
